import { useState, useRef, useEffect } from "react";
import { Canvas } from "@react-three/fiber";
import { Environment, ContactShadows } from "@react-three/drei";
import { EffectComposer, Bloom, Noise, Vignette, ChromaticAberration } from "@react-three/postprocessing"; 
import Avatar from "./components/Avatar";
import { sendMessageToGemini, stopResponse, continueResponse } from "./services/ai";
import "./App.css";

function App() {
  const [inputText, setInputText] = useState("");
  const [messages, setMessages] = useState([
    { sender: "ai", text: "Mata Melsa sudah terbuka, Tuan. Upload foto untuk aku lihat, atau suruh aku menggambar sesuatu yang nakal..." }
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [selectedImage, setSelectedImage] = useState(null); // State gambar upload
  
  const chatEndRef = useRef(null);
  const fileInputRef = useRef(null); // Ref untuk input file tersembunyi

  useEffect(() => {
    document.body.classList.toggle('light-mode', !isDarkMode);
  }, [isDarkMode]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Fungsi konversi file ke Base64
  const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        // Hapus prefix "data:image/jpeg;base64," agar bersih untuk API
        const base64Data = reader.result.split(',')[1]; 
        const mimeType = file.type;
        resolve({ mimeType, data: base64Data, preview: reader.result });
      };
      reader.onerror = error => reject(error);
    });
  };

  const handleFileSelect = async (e) => {
    const file = e.target.files[0];
    if (file) {
      const imageData = await fileToBase64(file);
      setSelectedImage(imageData);
    }
  };

  const handleSend = async () => {
    if (!inputText.trim() && !selectedImage) return;
    
    // Tampilkan pesan user
    const userMsg = { 
      sender: "user", 
      text: inputText, 
      image: selectedImage?.preview // Tampilkan preview di chat bubble user
    };
    
    setMessages((prev) => [...prev, userMsg]);
    
    const imagePayload = selectedImage ? { mimeType: selectedImage.mimeType, data: selectedImage.data } : null;
    
    // Reset input
    setInputText("");
    setSelectedImage(null);
    setIsLoading(true);

    // Kirim ke AI
    const replyText = await sendMessageToGemini(userMsg.text, imagePayload);
    setMessages((prev) => [...prev, { sender: "ai", text: replyText }]);
    setIsLoading(false);
  };

  const handleStop = () => {
    stopResponse();
    setIsLoading(false);
    setMessages((prev) => [...prev, { sender: "system", text: "⛔ BERHENTI." }]);
  };

  const handleContinue = async () => {
    setIsLoading(true);
    const replyText = await continueResponse();
    setMessages((prev) => [...prev, { sender: "ai", text: replyText }]);
    setIsLoading(false);
  };

  const toggleTheme = () => setIsDarkMode(!isDarkMode);

  // --- IMAGE PARSER (Render !!IMG:[]!! jadi Gambar) ---
  const renderMessageContent = (text) => {
    // Regex untuk menangkap !!IMG:[prompt]!!
    const parts = text.split(/(!!IMG:\[.*?\]!!)/g);
    
    return parts.map((part, index) => {
      if (part.startsWith("!!IMG:[")) {
        const prompt = part.replace("!!IMG:[", "").replace("]!!", "");
        // Gunakan Pollinations.ai (Gratis, Unlimited)
        const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=800&height=600&nologo=true&enhance=true`;
        
        return (
          <div key={index} className="generated-image-container">
            <img 
              src={imageUrl} 
              alt="Generated by Melsa" 
              className="generated-image" 
              loading="lazy"
              onError={(e) => e.target.style.display = 'none'} 
            />
            <div className="img-caption">🎨 {prompt}</div>
          </div>
        );
      }
      return <span key={index}>{part}</span>;
    });
  };

  // Warna 3D
  const bgColor = isDarkMode ? "#050005" : "#fff0f5";
  const fogColor = isDarkMode ? "#1a001a" : "#ffffff";

  return (
    <div className="app-container">
      
      {/* 3D LAYER */}
      <div className="canvas-layer">
        <Canvas camera={{ position: [0, 0, 6], fov: 35 }} gl={{ antialias: true }}>
          <color attach="background" args={[bgColor]} />
          <fog attach="fog" args={[fogColor, 5, 20]} />
          
          <ambientLight intensity={isDarkMode ? 0.2 : 0.8} color={isDarkMode ? "#ff0055" : "#ffffff"} />
          <spotLight position={[5, 5, 5]} intensity={isDarkMode ? 2 : 1} color={isDarkMode ? "#ff0055" : "#ff99cc"} angle={0.5} penumbra={1} castShadow />
          <spotLight position={[-5, -5, 5]} intensity={isDarkMode ? 2 : 1} color={isDarkMode ? "#bd00ff" : "#cc99ff"} angle={0.5} penumbra={1} />
          
          <Environment preset={isDarkMode ? "night" : "sunset"} blur={0.8} background={false} />
          <Avatar isThinking={isLoading} isDarkMode={isDarkMode} />
          <ContactShadows position={[0, -2, 0]} opacity={isDarkMode ? 0.6 : 0.3} scale={10} blur={3} color={isDarkMode ? "#550022" : "#aa5577"} />

          <EffectComposer disableNormalPass>
             <Bloom luminanceThreshold={isDarkMode ? 0.2 : 0.6} intensity={isDarkMode ? 1.5 : 0.8} radius={0.7} mipmapBlur />
             <Noise opacity={isDarkMode ? 0.05 : 0.02} />
             <Vignette eskil={false} offset={0.1} darkness={isDarkMode ? 1.3 : 0.6} />
             {isLoading && <ChromaticAberration offset={[0.002, 0.002]} />}
          </EffectComposer>
        </Canvas>
      </div>

      {/* UI LAYER */}
      <div className="ui-layer">
        
        <div className="hud-header">
          <div className="status-display">
            <span className={`status-dot ${isLoading ? 'busy' : 'ready'}`}></span>
            <span className="status-text">{isLoading ? 'MELSA SEDANG MELUKIS...' : 'MELSA VISUAL ONLINE'}</span>
          </div>
          <button className="theme-toggle-btn" onClick={toggleTheme}>
            {isDarkMode ? "☀️" : "🌙"}
          </button>
        </div>

        <div className="chat-feed">
          {messages.map((msg, index) => (
            <div key={index} className={`msg-row ${msg.sender}`}>
              <div className="msg-content">
                {/* Tampilkan gambar upload user jika ada */}
                {msg.image && <img src={msg.image} className="user-upload-preview" alt="Upload" />}
                {/* Render teks + gambar AI */}
                {renderMessageContent(msg.text)}
              </div>
            </div>
          ))}
          {isLoading && <div className="msg-row ai"><div className="msg-content loading-pulse">...</div></div>}
          <div ref={chatEndRef} />
        </div>

        <div className="hud-footer">
          <div className="action-bar">
            {isLoading ? (
              <button className="ctrl-btn stop" onClick={handleStop}>HENTIKAN</button>
            ) : (
              <button className="ctrl-btn" onClick={handleContinue}>LANJUTKAN</button>
            )}
          </div>

          <div className="input-dock">
            {/* Input File Tersembunyi */}
            <input 
              type="file" 
              ref={fileInputRef}
              accept="image/*"
              style={{display: 'none'}}
              onChange={handleFileSelect}
            />
            
            {/* Tombol Upload */}
            <button className="icon-btn" onClick={() => fileInputRef.current.click()}>
              📷
            </button>

            {/* Preview Kecil di dalam Input jika ada gambar dipilih */}
            {selectedImage && (
              <div className="mini-preview" onClick={() => setSelectedImage(null)}>
                <img src={selectedImage.preview} alt="Selected" />
                <span className="remove-x">×</span>
              </div>
            )}

            <input 
              type="text" 
              placeholder="Perintahkan aku (Gambar/Teks)..." 
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSend()}
              disabled={isLoading}
            />
            <button className="send-btn" onClick={handleSend} disabled={isLoading}>
              KIRIM
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}

export default App;